# Automatically generated by SST
import sst

# Define SST Program Options:
# (These reflect the settings from original run and are not necessary in all files)
sst.setProgramOption("verbose", "0")
sst.setProgramOption("stop-at", "25us")
sst.setProgramOption("print-timing-info", "false")
sst.setProgramOption("heartbeat-period", "")
sst.setProgramOption("timebase", "1 ps")
sst.setProgramOption("partitioner", "sst.single")
sst.setProgramOption("timeVortex", "sst.timevortex.priority_queue")
sst.setProgramOption("interthread-links", "false")
sst.setProgramOption("output-prefix-core", "@x SST Core: ")
# Define the global parameter sets:

# Define the SST Components:
comp_c0_0 = sst.Component("c0_0", "coreTestElement.coreTestComponent")
comp_c0_0.addParams({
     "workPerCycle" : "1000",
     "commSize" : "100",
     "commFreq" : "1000"
})
comp_c0_0.setCoordinates(0, 0, 0)
link_id_00000000 = sst.Link("link_id_00000000")
comp_c0_0.addLink(link_id_00000000, "Nlink", "10 ns")
link_id_00000001 = sst.Link("link_id_00000001")
comp_c0_0.addLink(link_id_00000001, "Slink", "10 ns")
link_id_00000002 = sst.Link("link_id_00000002")
comp_c0_0.addLink(link_id_00000002, "Elink", "10 ns")
link_id_00000003 = sst.Link("link_id_00000003")
comp_c0_0.addLink(link_id_00000003, "Wlink", "10 ns")

comp_c1_0 = sst.Component("c1_0", "coreTestElement.coreTestComponent")
comp_c1_0.addParams({
     "workPerCycle" : "1000",
     "commSize" : "100",
     "commFreq" : "1000"
})
comp_c1_0.setCoordinates(0, 0, 0)
comp_c1_0.addLink(link_id_00000002, "Wlink", "10 ns")
link_id_00000004 = sst.Link("link_id_00000004")
comp_c1_0.addLink(link_id_00000004, "Nlink", "10 ns")
link_id_00000005 = sst.Link("link_id_00000005")
comp_c1_0.addLink(link_id_00000005, "Slink", "10 ns")
link_id_00000006 = sst.Link("link_id_00000006")
comp_c1_0.addLink(link_id_00000006, "Elink", "10 ns")

comp_c2_0 = sst.Component("c2_0", "coreTestElement.coreTestComponent")
comp_c2_0.addParams({
     "workPerCycle" : "1000",
     "commSize" : "100",
     "commFreq" : "1000"
})
comp_c2_0.setCoordinates(0, 0, 0)
comp_c2_0.addLink(link_id_00000006, "Wlink", "10 ns")
link_id_00000007 = sst.Link("link_id_00000007")
comp_c2_0.addLink(link_id_00000007, "Nlink", "10 ns")
link_id_00000008 = sst.Link("link_id_00000008")
comp_c2_0.addLink(link_id_00000008, "Slink", "10 ns")
link_id_00000009 = sst.Link("link_id_00000009")
comp_c2_0.addLink(link_id_00000009, "Elink", "10 ns")

comp_c3_0 = sst.Component("c3_0", "coreTestElement.coreTestComponent")
comp_c3_0.addParams({
     "workPerCycle" : "1000",
     "commSize" : "100",
     "commFreq" : "1000"
})
comp_c3_0.setCoordinates(0, 0, 0)
comp_c3_0.addLink(link_id_00000009, "Wlink", "10 ns")
link_id_0000000a = sst.Link("link_id_0000000a")
comp_c3_0.addLink(link_id_0000000a, "Nlink", "10 ns")
link_id_0000000b = sst.Link("link_id_0000000b")
comp_c3_0.addLink(link_id_0000000b, "Slink", "10 ns")
link_id_0000000c = sst.Link("link_id_0000000c")
comp_c3_0.addLink(link_id_0000000c, "Elink", "10 ns")

comp_c4_0 = sst.Component("c4_0", "coreTestElement.coreTestComponent")
comp_c4_0.addParams({
     "workPerCycle" : "1000",
     "commSize" : "100",
     "commFreq" : "1000"
})
comp_c4_0.setCoordinates(0, 0, 0)
comp_c4_0.addLink(link_id_0000000c, "Wlink", "10 ns")
link_id_0000000d = sst.Link("link_id_0000000d")
comp_c4_0.addLink(link_id_0000000d, "Nlink", "10 ns")
link_id_0000000e = sst.Link("link_id_0000000e")
comp_c4_0.addLink(link_id_0000000e, "Slink", "10 ns")
link_id_0000000f = sst.Link("link_id_0000000f")
comp_c4_0.addLink(link_id_0000000f, "Elink", "10 ns")

comp_c5_0 = sst.Component("c5_0", "coreTestElement.coreTestComponent")
comp_c5_0.addParams({
     "workPerCycle" : "1000",
     "commSize" : "100",
     "commFreq" : "1000"
})
comp_c5_0.setCoordinates(0, 0, 0)
comp_c5_0.addLink(link_id_0000000f, "Wlink", "10 ns")
link_id_00000010 = sst.Link("link_id_00000010")
comp_c5_0.addLink(link_id_00000010, "Nlink", "10 ns")
link_id_00000011 = sst.Link("link_id_00000011")
comp_c5_0.addLink(link_id_00000011, "Slink", "10 ns")
link_id_00000012 = sst.Link("link_id_00000012")
comp_c5_0.addLink(link_id_00000012, "Elink", "10 ns")

comp_c6_0 = sst.Component("c6_0", "coreTestElement.coreTestComponent")
comp_c6_0.addParams({
     "workPerCycle" : "1000",
     "commSize" : "100",
     "commFreq" : "1000"
})
comp_c6_0.setCoordinates(0, 0, 0)
comp_c6_0.addLink(link_id_00000012, "Wlink", "10 ns")
link_id_00000013 = sst.Link("link_id_00000013")
comp_c6_0.addLink(link_id_00000013, "Nlink", "10 ns")
link_id_00000014 = sst.Link("link_id_00000014")
comp_c6_0.addLink(link_id_00000014, "Slink", "10 ns")
link_id_00000015 = sst.Link("link_id_00000015")
comp_c6_0.addLink(link_id_00000015, "Elink", "10 ns")

comp_c7_0 = sst.Component("c7_0", "coreTestElement.coreTestComponent")
comp_c7_0.addParams({
     "workPerCycle" : "1000",
     "commSize" : "100",
     "commFreq" : "1000"
})
comp_c7_0.setCoordinates(0, 0, 0)
comp_c7_0.addLink(link_id_00000015, "Wlink", "10 ns")
link_id_00000016 = sst.Link("link_id_00000016")
comp_c7_0.addLink(link_id_00000016, "Nlink", "10 ns")
link_id_00000017 = sst.Link("link_id_00000017")
comp_c7_0.addLink(link_id_00000017, "Slink", "10 ns")
link_id_00000018 = sst.Link("link_id_00000018")
comp_c7_0.addLink(link_id_00000018, "Elink", "10 ns")

comp_c8_0 = sst.Component("c8_0", "coreTestElement.coreTestComponent")
comp_c8_0.addParams({
     "workPerCycle" : "1000",
     "commSize" : "100",
     "commFreq" : "1000"
})
comp_c8_0.setCoordinates(0, 0, 0)
comp_c8_0.addLink(link_id_00000018, "Wlink", "10 ns")
link_id_00000019 = sst.Link("link_id_00000019")
comp_c8_0.addLink(link_id_00000019, "Nlink", "10 ns")
link_id_0000001a = sst.Link("link_id_0000001a")
comp_c8_0.addLink(link_id_0000001a, "Slink", "10 ns")
link_id_0000001b = sst.Link("link_id_0000001b")
comp_c8_0.addLink(link_id_0000001b, "Elink", "10 ns")

comp_c9_0 = sst.Component("c9_0", "coreTestElement.coreTestComponent")
comp_c9_0.addParams({
     "workPerCycle" : "1000",
     "commSize" : "100",
     "commFreq" : "1000"
})
comp_c9_0.setCoordinates(0, 0, 0)
comp_c9_0.addLink(link_id_00000003, "Elink", "10 ns")
comp_c9_0.addLink(link_id_0000001b, "Wlink", "10 ns")
link_id_0000001c = sst.Link("link_id_0000001c")
comp_c9_0.addLink(link_id_0000001c, "Nlink", "10 ns")
link_id_0000001d = sst.Link("link_id_0000001d")
comp_c9_0.addLink(link_id_0000001d, "Slink", "10 ns")

comp_c0_1 = sst.Component("c0_1", "coreTestElement.coreTestComponent")
comp_c0_1.addParams({
     "workPerCycle" : "1000",
     "commSize" : "100",
     "commFreq" : "1000"
})
comp_c0_1.setCoordinates(0, 0, 0)
comp_c0_1.addLink(link_id_00000000, "Slink", "10 ns")
link_id_0000001e = sst.Link("link_id_0000001e")
comp_c0_1.addLink(link_id_0000001e, "Nlink", "10 ns")
link_id_0000001f = sst.Link("link_id_0000001f")
comp_c0_1.addLink(link_id_0000001f, "Elink", "10 ns")
link_id_00000020 = sst.Link("link_id_00000020")
comp_c0_1.addLink(link_id_00000020, "Wlink", "10 ns")

comp_c1_1 = sst.Component("c1_1", "coreTestElement.coreTestComponent")
comp_c1_1.addParams({
     "workPerCycle" : "1000",
     "commSize" : "100",
     "commFreq" : "1000"
})
comp_c1_1.setCoordinates(0, 0, 0)
comp_c1_1.addLink(link_id_00000004, "Slink", "10 ns")
comp_c1_1.addLink(link_id_0000001f, "Wlink", "10 ns")
link_id_00000021 = sst.Link("link_id_00000021")
comp_c1_1.addLink(link_id_00000021, "Nlink", "10 ns")
link_id_00000022 = sst.Link("link_id_00000022")
comp_c1_1.addLink(link_id_00000022, "Elink", "10 ns")

comp_c2_1 = sst.Component("c2_1", "coreTestElement.coreTestComponent")
comp_c2_1.addParams({
     "workPerCycle" : "1000",
     "commSize" : "100",
     "commFreq" : "1000"
})
comp_c2_1.setCoordinates(0, 0, 0)
comp_c2_1.addLink(link_id_00000007, "Slink", "10 ns")
comp_c2_1.addLink(link_id_00000022, "Wlink", "10 ns")
link_id_00000023 = sst.Link("link_id_00000023")
comp_c2_1.addLink(link_id_00000023, "Nlink", "10 ns")
link_id_00000024 = sst.Link("link_id_00000024")
comp_c2_1.addLink(link_id_00000024, "Elink", "10 ns")

comp_c3_1 = sst.Component("c3_1", "coreTestElement.coreTestComponent")
comp_c3_1.addParams({
     "workPerCycle" : "1000",
     "commSize" : "100",
     "commFreq" : "1000"
})
comp_c3_1.setCoordinates(0, 0, 0)
comp_c3_1.addLink(link_id_0000000a, "Slink", "10 ns")
comp_c3_1.addLink(link_id_00000024, "Wlink", "10 ns")
link_id_00000025 = sst.Link("link_id_00000025")
comp_c3_1.addLink(link_id_00000025, "Nlink", "10 ns")
link_id_00000026 = sst.Link("link_id_00000026")
comp_c3_1.addLink(link_id_00000026, "Elink", "10 ns")

comp_c4_1 = sst.Component("c4_1", "coreTestElement.coreTestComponent")
comp_c4_1.addParams({
     "workPerCycle" : "1000",
     "commSize" : "100",
     "commFreq" : "1000"
})
comp_c4_1.setCoordinates(0, 0, 0)
comp_c4_1.addLink(link_id_0000000d, "Slink", "10 ns")
comp_c4_1.addLink(link_id_00000026, "Wlink", "10 ns")
link_id_00000027 = sst.Link("link_id_00000027")
comp_c4_1.addLink(link_id_00000027, "Nlink", "10 ns")
link_id_00000028 = sst.Link("link_id_00000028")
comp_c4_1.addLink(link_id_00000028, "Elink", "10 ns")

comp_c5_1 = sst.Component("c5_1", "coreTestElement.coreTestComponent")
comp_c5_1.addParams({
     "workPerCycle" : "1000",
     "commSize" : "100",
     "commFreq" : "1000"
})
comp_c5_1.setCoordinates(0, 0, 0)
comp_c5_1.addLink(link_id_00000010, "Slink", "10 ns")
comp_c5_1.addLink(link_id_00000028, "Wlink", "10 ns")
link_id_00000029 = sst.Link("link_id_00000029")
comp_c5_1.addLink(link_id_00000029, "Nlink", "10 ns")
link_id_0000002a = sst.Link("link_id_0000002a")
comp_c5_1.addLink(link_id_0000002a, "Elink", "10 ns")

comp_c6_1 = sst.Component("c6_1", "coreTestElement.coreTestComponent")
comp_c6_1.addParams({
     "workPerCycle" : "1000",
     "commSize" : "100",
     "commFreq" : "1000"
})
comp_c6_1.setCoordinates(0, 0, 0)
comp_c6_1.addLink(link_id_00000013, "Slink", "10 ns")
comp_c6_1.addLink(link_id_0000002a, "Wlink", "10 ns")
link_id_0000002b = sst.Link("link_id_0000002b")
comp_c6_1.addLink(link_id_0000002b, "Nlink", "10 ns")
link_id_0000002c = sst.Link("link_id_0000002c")
comp_c6_1.addLink(link_id_0000002c, "Elink", "10 ns")

comp_c7_1 = sst.Component("c7_1", "coreTestElement.coreTestComponent")
comp_c7_1.addParams({
     "workPerCycle" : "1000",
     "commSize" : "100",
     "commFreq" : "1000"
})
comp_c7_1.setCoordinates(0, 0, 0)
comp_c7_1.addLink(link_id_00000016, "Slink", "10 ns")
comp_c7_1.addLink(link_id_0000002c, "Wlink", "10 ns")
link_id_0000002d = sst.Link("link_id_0000002d")
comp_c7_1.addLink(link_id_0000002d, "Nlink", "10 ns")
link_id_0000002e = sst.Link("link_id_0000002e")
comp_c7_1.addLink(link_id_0000002e, "Elink", "10 ns")

comp_c8_1 = sst.Component("c8_1", "coreTestElement.coreTestComponent")
comp_c8_1.addParams({
     "workPerCycle" : "1000",
     "commSize" : "100",
     "commFreq" : "1000"
})
comp_c8_1.setCoordinates(0, 0, 0)
comp_c8_1.addLink(link_id_00000019, "Slink", "10 ns")
comp_c8_1.addLink(link_id_0000002e, "Wlink", "10 ns")
link_id_0000002f = sst.Link("link_id_0000002f")
comp_c8_1.addLink(link_id_0000002f, "Nlink", "10 ns")
link_id_00000030 = sst.Link("link_id_00000030")
comp_c8_1.addLink(link_id_00000030, "Elink", "10 ns")

comp_c9_1 = sst.Component("c9_1", "coreTestElement.coreTestComponent")
comp_c9_1.addParams({
     "workPerCycle" : "1000",
     "commSize" : "100",
     "commFreq" : "1000"
})
comp_c9_1.setCoordinates(0, 0, 0)
comp_c9_1.addLink(link_id_0000001c, "Slink", "10 ns")
comp_c9_1.addLink(link_id_00000020, "Elink", "10 ns")
comp_c9_1.addLink(link_id_00000030, "Wlink", "10 ns")
link_id_00000031 = sst.Link("link_id_00000031")
comp_c9_1.addLink(link_id_00000031, "Nlink", "10 ns")

comp_c0_2 = sst.Component("c0_2", "coreTestElement.coreTestComponent")
comp_c0_2.addParams({
     "workPerCycle" : "1000",
     "commSize" : "100",
     "commFreq" : "1000"
})
comp_c0_2.setCoordinates(0, 0, 0)
comp_c0_2.addLink(link_id_0000001e, "Slink", "10 ns")
link_id_00000032 = sst.Link("link_id_00000032")
comp_c0_2.addLink(link_id_00000032, "Nlink", "10 ns")
link_id_00000033 = sst.Link("link_id_00000033")
comp_c0_2.addLink(link_id_00000033, "Elink", "10 ns")
link_id_00000034 = sst.Link("link_id_00000034")
comp_c0_2.addLink(link_id_00000034, "Wlink", "10 ns")

comp_c1_2 = sst.Component("c1_2", "coreTestElement.coreTestComponent")
comp_c1_2.addParams({
     "workPerCycle" : "1000",
     "commSize" : "100",
     "commFreq" : "1000"
})
comp_c1_2.setCoordinates(0, 0, 0)
comp_c1_2.addLink(link_id_00000021, "Slink", "10 ns")
comp_c1_2.addLink(link_id_00000033, "Wlink", "10 ns")
link_id_00000035 = sst.Link("link_id_00000035")
comp_c1_2.addLink(link_id_00000035, "Nlink", "10 ns")
link_id_00000036 = sst.Link("link_id_00000036")
comp_c1_2.addLink(link_id_00000036, "Elink", "10 ns")

comp_c2_2 = sst.Component("c2_2", "coreTestElement.coreTestComponent")
comp_c2_2.addParams({
     "workPerCycle" : "1000",
     "commSize" : "100",
     "commFreq" : "1000"
})
comp_c2_2.setCoordinates(0, 0, 0)
comp_c2_2.addLink(link_id_00000023, "Slink", "10 ns")
comp_c2_2.addLink(link_id_00000036, "Wlink", "10 ns")
link_id_00000037 = sst.Link("link_id_00000037")
comp_c2_2.addLink(link_id_00000037, "Nlink", "10 ns")
link_id_00000038 = sst.Link("link_id_00000038")
comp_c2_2.addLink(link_id_00000038, "Elink", "10 ns")

comp_c3_2 = sst.Component("c3_2", "coreTestElement.coreTestComponent")
comp_c3_2.addParams({
     "workPerCycle" : "1000",
     "commSize" : "100",
     "commFreq" : "1000"
})
comp_c3_2.setCoordinates(0, 0, 0)
comp_c3_2.addLink(link_id_00000025, "Slink", "10 ns")
comp_c3_2.addLink(link_id_00000038, "Wlink", "10 ns")
link_id_00000039 = sst.Link("link_id_00000039")
comp_c3_2.addLink(link_id_00000039, "Nlink", "10 ns")
link_id_0000003a = sst.Link("link_id_0000003a")
comp_c3_2.addLink(link_id_0000003a, "Elink", "10 ns")

comp_c4_2 = sst.Component("c4_2", "coreTestElement.coreTestComponent")
comp_c4_2.addParams({
     "workPerCycle" : "1000",
     "commSize" : "100",
     "commFreq" : "1000"
})
comp_c4_2.setCoordinates(0, 0, 0)
comp_c4_2.addLink(link_id_00000027, "Slink", "10 ns")
comp_c4_2.addLink(link_id_0000003a, "Wlink", "10 ns")
link_id_0000003b = sst.Link("link_id_0000003b")
comp_c4_2.addLink(link_id_0000003b, "Nlink", "10 ns")
link_id_0000003c = sst.Link("link_id_0000003c")
comp_c4_2.addLink(link_id_0000003c, "Elink", "10 ns")

comp_c5_2 = sst.Component("c5_2", "coreTestElement.coreTestComponent")
comp_c5_2.addParams({
     "workPerCycle" : "1000",
     "commSize" : "100",
     "commFreq" : "1000"
})
comp_c5_2.setCoordinates(0, 0, 0)
comp_c5_2.addLink(link_id_00000029, "Slink", "10 ns")
comp_c5_2.addLink(link_id_0000003c, "Wlink", "10 ns")
link_id_0000003d = sst.Link("link_id_0000003d")
comp_c5_2.addLink(link_id_0000003d, "Nlink", "10 ns")
link_id_0000003e = sst.Link("link_id_0000003e")
comp_c5_2.addLink(link_id_0000003e, "Elink", "10 ns")

comp_c6_2 = sst.Component("c6_2", "coreTestElement.coreTestComponent")
comp_c6_2.addParams({
     "workPerCycle" : "1000",
     "commSize" : "100",
     "commFreq" : "1000"
})
comp_c6_2.setCoordinates(0, 0, 0)
comp_c6_2.addLink(link_id_0000002b, "Slink", "10 ns")
comp_c6_2.addLink(link_id_0000003e, "Wlink", "10 ns")
link_id_0000003f = sst.Link("link_id_0000003f")
comp_c6_2.addLink(link_id_0000003f, "Nlink", "10 ns")
link_id_00000040 = sst.Link("link_id_00000040")
comp_c6_2.addLink(link_id_00000040, "Elink", "10 ns")

comp_c7_2 = sst.Component("c7_2", "coreTestElement.coreTestComponent")
comp_c7_2.addParams({
     "workPerCycle" : "1000",
     "commSize" : "100",
     "commFreq" : "1000"
})
comp_c7_2.setCoordinates(0, 0, 0)
comp_c7_2.addLink(link_id_0000002d, "Slink", "10 ns")
comp_c7_2.addLink(link_id_00000040, "Wlink", "10 ns")
link_id_00000041 = sst.Link("link_id_00000041")
comp_c7_2.addLink(link_id_00000041, "Nlink", "10 ns")
link_id_00000042 = sst.Link("link_id_00000042")
comp_c7_2.addLink(link_id_00000042, "Elink", "10 ns")

comp_c8_2 = sst.Component("c8_2", "coreTestElement.coreTestComponent")
comp_c8_2.addParams({
     "workPerCycle" : "1000",
     "commSize" : "100",
     "commFreq" : "1000"
})
comp_c8_2.setCoordinates(0, 0, 0)
comp_c8_2.addLink(link_id_0000002f, "Slink", "10 ns")
comp_c8_2.addLink(link_id_00000042, "Wlink", "10 ns")
link_id_00000043 = sst.Link("link_id_00000043")
comp_c8_2.addLink(link_id_00000043, "Nlink", "10 ns")
link_id_00000044 = sst.Link("link_id_00000044")
comp_c8_2.addLink(link_id_00000044, "Elink", "10 ns")

comp_c9_2 = sst.Component("c9_2", "coreTestElement.coreTestComponent")
comp_c9_2.addParams({
     "workPerCycle" : "1000",
     "commSize" : "100",
     "commFreq" : "1000"
})
comp_c9_2.setCoordinates(0, 0, 0)
comp_c9_2.addLink(link_id_00000031, "Slink", "10 ns")
comp_c9_2.addLink(link_id_00000034, "Elink", "10 ns")
comp_c9_2.addLink(link_id_00000044, "Wlink", "10 ns")
link_id_00000045 = sst.Link("link_id_00000045")
comp_c9_2.addLink(link_id_00000045, "Nlink", "10 ns")

comp_c0_3 = sst.Component("c0_3", "coreTestElement.coreTestComponent")
comp_c0_3.addParams({
     "workPerCycle" : "1000",
     "commSize" : "100",
     "commFreq" : "1000"
})
comp_c0_3.setCoordinates(0, 0, 0)
comp_c0_3.addLink(link_id_00000032, "Slink", "10 ns")
link_id_00000046 = sst.Link("link_id_00000046")
comp_c0_3.addLink(link_id_00000046, "Nlink", "10 ns")
link_id_00000047 = sst.Link("link_id_00000047")
comp_c0_3.addLink(link_id_00000047, "Elink", "10 ns")
link_id_00000048 = sst.Link("link_id_00000048")
comp_c0_3.addLink(link_id_00000048, "Wlink", "10 ns")

comp_c1_3 = sst.Component("c1_3", "coreTestElement.coreTestComponent")
comp_c1_3.addParams({
     "workPerCycle" : "1000",
     "commSize" : "100",
     "commFreq" : "1000"
})
comp_c1_3.setCoordinates(0, 0, 0)
comp_c1_3.addLink(link_id_00000035, "Slink", "10 ns")
comp_c1_3.addLink(link_id_00000047, "Wlink", "10 ns")
link_id_00000049 = sst.Link("link_id_00000049")
comp_c1_3.addLink(link_id_00000049, "Nlink", "10 ns")
link_id_0000004a = sst.Link("link_id_0000004a")
comp_c1_3.addLink(link_id_0000004a, "Elink", "10 ns")

comp_c2_3 = sst.Component("c2_3", "coreTestElement.coreTestComponent")
comp_c2_3.addParams({
     "workPerCycle" : "1000",
     "commSize" : "100",
     "commFreq" : "1000"
})
comp_c2_3.setCoordinates(0, 0, 0)
comp_c2_3.addLink(link_id_00000037, "Slink", "10 ns")
comp_c2_3.addLink(link_id_0000004a, "Wlink", "10 ns")
link_id_0000004b = sst.Link("link_id_0000004b")
comp_c2_3.addLink(link_id_0000004b, "Nlink", "10 ns")
link_id_0000004c = sst.Link("link_id_0000004c")
comp_c2_3.addLink(link_id_0000004c, "Elink", "10 ns")

comp_c3_3 = sst.Component("c3_3", "coreTestElement.coreTestComponent")
comp_c3_3.addParams({
     "workPerCycle" : "1000",
     "commSize" : "100",
     "commFreq" : "1000"
})
comp_c3_3.setCoordinates(0, 0, 0)
comp_c3_3.addLink(link_id_00000039, "Slink", "10 ns")
comp_c3_3.addLink(link_id_0000004c, "Wlink", "10 ns")
link_id_0000004d = sst.Link("link_id_0000004d")
comp_c3_3.addLink(link_id_0000004d, "Nlink", "10 ns")
link_id_0000004e = sst.Link("link_id_0000004e")
comp_c3_3.addLink(link_id_0000004e, "Elink", "10 ns")

comp_c4_3 = sst.Component("c4_3", "coreTestElement.coreTestComponent")
comp_c4_3.addParams({
     "workPerCycle" : "1000",
     "commSize" : "100",
     "commFreq" : "1000"
})
comp_c4_3.setCoordinates(0, 0, 0)
comp_c4_3.addLink(link_id_0000003b, "Slink", "10 ns")
comp_c4_3.addLink(link_id_0000004e, "Wlink", "10 ns")
link_id_0000004f = sst.Link("link_id_0000004f")
comp_c4_3.addLink(link_id_0000004f, "Nlink", "10 ns")
link_id_00000050 = sst.Link("link_id_00000050")
comp_c4_3.addLink(link_id_00000050, "Elink", "10 ns")

comp_c5_3 = sst.Component("c5_3", "coreTestElement.coreTestComponent")
comp_c5_3.addParams({
     "workPerCycle" : "1000",
     "commSize" : "100",
     "commFreq" : "1000"
})
comp_c5_3.setCoordinates(0, 0, 0)
comp_c5_3.addLink(link_id_0000003d, "Slink", "10 ns")
comp_c5_3.addLink(link_id_00000050, "Wlink", "10 ns")
link_id_00000051 = sst.Link("link_id_00000051")
comp_c5_3.addLink(link_id_00000051, "Nlink", "10 ns")
link_id_00000052 = sst.Link("link_id_00000052")
comp_c5_3.addLink(link_id_00000052, "Elink", "10 ns")

comp_c6_3 = sst.Component("c6_3", "coreTestElement.coreTestComponent")
comp_c6_3.addParams({
     "workPerCycle" : "1000",
     "commSize" : "100",
     "commFreq" : "1000"
})
comp_c6_3.setCoordinates(0, 0, 0)
comp_c6_3.addLink(link_id_0000003f, "Slink", "10 ns")
comp_c6_3.addLink(link_id_00000052, "Wlink", "10 ns")
link_id_00000053 = sst.Link("link_id_00000053")
comp_c6_3.addLink(link_id_00000053, "Nlink", "10 ns")
link_id_00000054 = sst.Link("link_id_00000054")
comp_c6_3.addLink(link_id_00000054, "Elink", "10 ns")

comp_c7_3 = sst.Component("c7_3", "coreTestElement.coreTestComponent")
comp_c7_3.addParams({
     "workPerCycle" : "1000",
     "commSize" : "100",
     "commFreq" : "1000"
})
comp_c7_3.setCoordinates(0, 0, 0)
comp_c7_3.addLink(link_id_00000041, "Slink", "10 ns")
comp_c7_3.addLink(link_id_00000054, "Wlink", "10 ns")
link_id_00000055 = sst.Link("link_id_00000055")
comp_c7_3.addLink(link_id_00000055, "Nlink", "10 ns")
link_id_00000056 = sst.Link("link_id_00000056")
comp_c7_3.addLink(link_id_00000056, "Elink", "10 ns")

comp_c8_3 = sst.Component("c8_3", "coreTestElement.coreTestComponent")
comp_c8_3.addParams({
     "workPerCycle" : "1000",
     "commSize" : "100",
     "commFreq" : "1000"
})
comp_c8_3.setCoordinates(0, 0, 0)
comp_c8_3.addLink(link_id_00000043, "Slink", "10 ns")
comp_c8_3.addLink(link_id_00000056, "Wlink", "10 ns")
link_id_00000057 = sst.Link("link_id_00000057")
comp_c8_3.addLink(link_id_00000057, "Nlink", "10 ns")
link_id_00000058 = sst.Link("link_id_00000058")
comp_c8_3.addLink(link_id_00000058, "Elink", "10 ns")

comp_c9_3 = sst.Component("c9_3", "coreTestElement.coreTestComponent")
comp_c9_3.addParams({
     "workPerCycle" : "1000",
     "commSize" : "100",
     "commFreq" : "1000"
})
comp_c9_3.setCoordinates(0, 0, 0)
comp_c9_3.addLink(link_id_00000045, "Slink", "10 ns")
comp_c9_3.addLink(link_id_00000048, "Elink", "10 ns")
comp_c9_3.addLink(link_id_00000058, "Wlink", "10 ns")
link_id_00000059 = sst.Link("link_id_00000059")
comp_c9_3.addLink(link_id_00000059, "Nlink", "10 ns")

comp_c0_4 = sst.Component("c0_4", "coreTestElement.coreTestComponent")
comp_c0_4.addParams({
     "workPerCycle" : "1000",
     "commSize" : "100",
     "commFreq" : "1000"
})
comp_c0_4.setCoordinates(0, 0, 0)
comp_c0_4.addLink(link_id_00000046, "Slink", "10 ns")
link_id_0000005a = sst.Link("link_id_0000005a")
comp_c0_4.addLink(link_id_0000005a, "Nlink", "10 ns")
link_id_0000005b = sst.Link("link_id_0000005b")
comp_c0_4.addLink(link_id_0000005b, "Elink", "10 ns")
link_id_0000005c = sst.Link("link_id_0000005c")
comp_c0_4.addLink(link_id_0000005c, "Wlink", "10 ns")

comp_c1_4 = sst.Component("c1_4", "coreTestElement.coreTestComponent")
comp_c1_4.addParams({
     "workPerCycle" : "1000",
     "commSize" : "100",
     "commFreq" : "1000"
})
comp_c1_4.setCoordinates(0, 0, 0)
comp_c1_4.addLink(link_id_00000049, "Slink", "10 ns")
comp_c1_4.addLink(link_id_0000005b, "Wlink", "10 ns")
link_id_0000005d = sst.Link("link_id_0000005d")
comp_c1_4.addLink(link_id_0000005d, "Nlink", "10 ns")
link_id_0000005e = sst.Link("link_id_0000005e")
comp_c1_4.addLink(link_id_0000005e, "Elink", "10 ns")

comp_c2_4 = sst.Component("c2_4", "coreTestElement.coreTestComponent")
comp_c2_4.addParams({
     "workPerCycle" : "1000",
     "commSize" : "100",
     "commFreq" : "1000"
})
comp_c2_4.setCoordinates(0, 0, 0)
comp_c2_4.addLink(link_id_0000004b, "Slink", "10 ns")
comp_c2_4.addLink(link_id_0000005e, "Wlink", "10 ns")
link_id_0000005f = sst.Link("link_id_0000005f")
comp_c2_4.addLink(link_id_0000005f, "Nlink", "10 ns")
link_id_00000060 = sst.Link("link_id_00000060")
comp_c2_4.addLink(link_id_00000060, "Elink", "10 ns")

comp_c3_4 = sst.Component("c3_4", "coreTestElement.coreTestComponent")
comp_c3_4.addParams({
     "workPerCycle" : "1000",
     "commSize" : "100",
     "commFreq" : "1000"
})
comp_c3_4.setCoordinates(0, 0, 0)
comp_c3_4.addLink(link_id_0000004d, "Slink", "10 ns")
comp_c3_4.addLink(link_id_00000060, "Wlink", "10 ns")
link_id_00000061 = sst.Link("link_id_00000061")
comp_c3_4.addLink(link_id_00000061, "Nlink", "10 ns")
link_id_00000062 = sst.Link("link_id_00000062")
comp_c3_4.addLink(link_id_00000062, "Elink", "10 ns")

comp_c4_4 = sst.Component("c4_4", "coreTestElement.coreTestComponent")
comp_c4_4.addParams({
     "workPerCycle" : "1000",
     "commSize" : "100",
     "commFreq" : "1000"
})
comp_c4_4.setCoordinates(0, 0, 0)
comp_c4_4.addLink(link_id_0000004f, "Slink", "10 ns")
comp_c4_4.addLink(link_id_00000062, "Wlink", "10 ns")
link_id_00000063 = sst.Link("link_id_00000063")
comp_c4_4.addLink(link_id_00000063, "Nlink", "10 ns")
link_id_00000064 = sst.Link("link_id_00000064")
comp_c4_4.addLink(link_id_00000064, "Elink", "10 ns")

comp_c5_4 = sst.Component("c5_4", "coreTestElement.coreTestComponent")
comp_c5_4.addParams({
     "workPerCycle" : "1000",
     "commSize" : "100",
     "commFreq" : "1000"
})
comp_c5_4.setCoordinates(0, 0, 0)
comp_c5_4.addLink(link_id_00000051, "Slink", "10 ns")
comp_c5_4.addLink(link_id_00000064, "Wlink", "10 ns")
link_id_00000065 = sst.Link("link_id_00000065")
comp_c5_4.addLink(link_id_00000065, "Nlink", "10 ns")
link_id_00000066 = sst.Link("link_id_00000066")
comp_c5_4.addLink(link_id_00000066, "Elink", "10 ns")

comp_c6_4 = sst.Component("c6_4", "coreTestElement.coreTestComponent")
comp_c6_4.addParams({
     "workPerCycle" : "1000",
     "commSize" : "100",
     "commFreq" : "1000"
})
comp_c6_4.setCoordinates(0, 0, 0)
comp_c6_4.addLink(link_id_00000053, "Slink", "10 ns")
comp_c6_4.addLink(link_id_00000066, "Wlink", "10 ns")
link_id_00000067 = sst.Link("link_id_00000067")
comp_c6_4.addLink(link_id_00000067, "Nlink", "10 ns")
link_id_00000068 = sst.Link("link_id_00000068")
comp_c6_4.addLink(link_id_00000068, "Elink", "10 ns")

comp_c7_4 = sst.Component("c7_4", "coreTestElement.coreTestComponent")
comp_c7_4.addParams({
     "workPerCycle" : "1000",
     "commSize" : "100",
     "commFreq" : "1000"
})
comp_c7_4.setCoordinates(0, 0, 0)
comp_c7_4.addLink(link_id_00000055, "Slink", "10 ns")
comp_c7_4.addLink(link_id_00000068, "Wlink", "10 ns")
link_id_00000069 = sst.Link("link_id_00000069")
comp_c7_4.addLink(link_id_00000069, "Nlink", "10 ns")
link_id_0000006a = sst.Link("link_id_0000006a")
comp_c7_4.addLink(link_id_0000006a, "Elink", "10 ns")

comp_c8_4 = sst.Component("c8_4", "coreTestElement.coreTestComponent")
comp_c8_4.addParams({
     "workPerCycle" : "1000",
     "commSize" : "100",
     "commFreq" : "1000"
})
comp_c8_4.setCoordinates(0, 0, 0)
comp_c8_4.addLink(link_id_00000057, "Slink", "10 ns")
comp_c8_4.addLink(link_id_0000006a, "Wlink", "10 ns")
link_id_0000006b = sst.Link("link_id_0000006b")
comp_c8_4.addLink(link_id_0000006b, "Nlink", "10 ns")
link_id_0000006c = sst.Link("link_id_0000006c")
comp_c8_4.addLink(link_id_0000006c, "Elink", "10 ns")

comp_c9_4 = sst.Component("c9_4", "coreTestElement.coreTestComponent")
comp_c9_4.addParams({
     "workPerCycle" : "1000",
     "commSize" : "100",
     "commFreq" : "1000"
})
comp_c9_4.setCoordinates(0, 0, 0)
comp_c9_4.addLink(link_id_00000059, "Slink", "10 ns")
comp_c9_4.addLink(link_id_0000005c, "Elink", "10 ns")
comp_c9_4.addLink(link_id_0000006c, "Wlink", "10 ns")
link_id_0000006d = sst.Link("link_id_0000006d")
comp_c9_4.addLink(link_id_0000006d, "Nlink", "10 ns")

comp_c0_5 = sst.Component("c0_5", "coreTestElement.coreTestComponent")
comp_c0_5.addParams({
     "workPerCycle" : "1000",
     "commSize" : "100",
     "commFreq" : "1000"
})
comp_c0_5.setCoordinates(0, 0, 0)
comp_c0_5.addLink(link_id_0000005a, "Slink", "10 ns")
link_id_0000006e = sst.Link("link_id_0000006e")
comp_c0_5.addLink(link_id_0000006e, "Nlink", "10 ns")
link_id_0000006f = sst.Link("link_id_0000006f")
comp_c0_5.addLink(link_id_0000006f, "Elink", "10 ns")
link_id_00000070 = sst.Link("link_id_00000070")
comp_c0_5.addLink(link_id_00000070, "Wlink", "10 ns")

comp_c1_5 = sst.Component("c1_5", "coreTestElement.coreTestComponent")
comp_c1_5.addParams({
     "workPerCycle" : "1000",
     "commSize" : "100",
     "commFreq" : "1000"
})
comp_c1_5.setCoordinates(0, 0, 0)
comp_c1_5.addLink(link_id_0000005d, "Slink", "10 ns")
comp_c1_5.addLink(link_id_0000006f, "Wlink", "10 ns")
link_id_00000071 = sst.Link("link_id_00000071")
comp_c1_5.addLink(link_id_00000071, "Nlink", "10 ns")
link_id_00000072 = sst.Link("link_id_00000072")
comp_c1_5.addLink(link_id_00000072, "Elink", "10 ns")

comp_c2_5 = sst.Component("c2_5", "coreTestElement.coreTestComponent")
comp_c2_5.addParams({
     "workPerCycle" : "1000",
     "commSize" : "100",
     "commFreq" : "1000"
})
comp_c2_5.setCoordinates(0, 0, 0)
comp_c2_5.addLink(link_id_0000005f, "Slink", "10 ns")
comp_c2_5.addLink(link_id_00000072, "Wlink", "10 ns")
link_id_00000073 = sst.Link("link_id_00000073")
comp_c2_5.addLink(link_id_00000073, "Nlink", "10 ns")
link_id_00000074 = sst.Link("link_id_00000074")
comp_c2_5.addLink(link_id_00000074, "Elink", "10 ns")

comp_c3_5 = sst.Component("c3_5", "coreTestElement.coreTestComponent")
comp_c3_5.addParams({
     "workPerCycle" : "1000",
     "commSize" : "100",
     "commFreq" : "1000"
})
comp_c3_5.setCoordinates(0, 0, 0)
comp_c3_5.addLink(link_id_00000061, "Slink", "10 ns")
comp_c3_5.addLink(link_id_00000074, "Wlink", "10 ns")
link_id_00000075 = sst.Link("link_id_00000075")
comp_c3_5.addLink(link_id_00000075, "Nlink", "10 ns")
link_id_00000076 = sst.Link("link_id_00000076")
comp_c3_5.addLink(link_id_00000076, "Elink", "10 ns")

comp_c4_5 = sst.Component("c4_5", "coreTestElement.coreTestComponent")
comp_c4_5.addParams({
     "workPerCycle" : "1000",
     "commSize" : "100",
     "commFreq" : "1000"
})
comp_c4_5.setCoordinates(0, 0, 0)
comp_c4_5.addLink(link_id_00000063, "Slink", "10 ns")
comp_c4_5.addLink(link_id_00000076, "Wlink", "10 ns")
link_id_00000077 = sst.Link("link_id_00000077")
comp_c4_5.addLink(link_id_00000077, "Nlink", "10 ns")
link_id_00000078 = sst.Link("link_id_00000078")
comp_c4_5.addLink(link_id_00000078, "Elink", "10 ns")

comp_c5_5 = sst.Component("c5_5", "coreTestElement.coreTestComponent")
comp_c5_5.addParams({
     "workPerCycle" : "1000",
     "commSize" : "100",
     "commFreq" : "1000"
})
comp_c5_5.setCoordinates(0, 0, 0)
comp_c5_5.addLink(link_id_00000065, "Slink", "10 ns")
comp_c5_5.addLink(link_id_00000078, "Wlink", "10 ns")
link_id_00000079 = sst.Link("link_id_00000079")
comp_c5_5.addLink(link_id_00000079, "Nlink", "10 ns")
link_id_0000007a = sst.Link("link_id_0000007a")
comp_c5_5.addLink(link_id_0000007a, "Elink", "10 ns")

comp_c6_5 = sst.Component("c6_5", "coreTestElement.coreTestComponent")
comp_c6_5.addParams({
     "workPerCycle" : "1000",
     "commSize" : "100",
     "commFreq" : "1000"
})
comp_c6_5.setCoordinates(0, 0, 0)
comp_c6_5.addLink(link_id_00000067, "Slink", "10 ns")
comp_c6_5.addLink(link_id_0000007a, "Wlink", "10 ns")
link_id_0000007b = sst.Link("link_id_0000007b")
comp_c6_5.addLink(link_id_0000007b, "Nlink", "10 ns")
link_id_0000007c = sst.Link("link_id_0000007c")
comp_c6_5.addLink(link_id_0000007c, "Elink", "10 ns")

comp_c7_5 = sst.Component("c7_5", "coreTestElement.coreTestComponent")
comp_c7_5.addParams({
     "workPerCycle" : "1000",
     "commSize" : "100",
     "commFreq" : "1000"
})
comp_c7_5.setCoordinates(0, 0, 0)
comp_c7_5.addLink(link_id_00000069, "Slink", "10 ns")
comp_c7_5.addLink(link_id_0000007c, "Wlink", "10 ns")
link_id_0000007d = sst.Link("link_id_0000007d")
comp_c7_5.addLink(link_id_0000007d, "Nlink", "10 ns")
link_id_0000007e = sst.Link("link_id_0000007e")
comp_c7_5.addLink(link_id_0000007e, "Elink", "10 ns")

comp_c8_5 = sst.Component("c8_5", "coreTestElement.coreTestComponent")
comp_c8_5.addParams({
     "workPerCycle" : "1000",
     "commSize" : "100",
     "commFreq" : "1000"
})
comp_c8_5.setCoordinates(0, 0, 0)
comp_c8_5.addLink(link_id_0000006b, "Slink", "10 ns")
comp_c8_5.addLink(link_id_0000007e, "Wlink", "10 ns")
link_id_0000007f = sst.Link("link_id_0000007f")
comp_c8_5.addLink(link_id_0000007f, "Nlink", "10 ns")
link_id_00000080 = sst.Link("link_id_00000080")
comp_c8_5.addLink(link_id_00000080, "Elink", "10 ns")

comp_c9_5 = sst.Component("c9_5", "coreTestElement.coreTestComponent")
comp_c9_5.addParams({
     "workPerCycle" : "1000",
     "commSize" : "100",
     "commFreq" : "1000"
})
comp_c9_5.setCoordinates(0, 0, 0)
comp_c9_5.addLink(link_id_0000006d, "Slink", "10 ns")
comp_c9_5.addLink(link_id_00000070, "Elink", "10 ns")
comp_c9_5.addLink(link_id_00000080, "Wlink", "10 ns")
link_id_00000081 = sst.Link("link_id_00000081")
comp_c9_5.addLink(link_id_00000081, "Nlink", "10 ns")

comp_c0_6 = sst.Component("c0_6", "coreTestElement.coreTestComponent")
comp_c0_6.addParams({
     "workPerCycle" : "1000",
     "commSize" : "100",
     "commFreq" : "1000"
})
comp_c0_6.setCoordinates(0, 0, 0)
comp_c0_6.addLink(link_id_0000006e, "Slink", "10 ns")
link_id_00000082 = sst.Link("link_id_00000082")
comp_c0_6.addLink(link_id_00000082, "Nlink", "10 ns")
link_id_00000083 = sst.Link("link_id_00000083")
comp_c0_6.addLink(link_id_00000083, "Elink", "10 ns")
link_id_00000084 = sst.Link("link_id_00000084")
comp_c0_6.addLink(link_id_00000084, "Wlink", "10 ns")

comp_c1_6 = sst.Component("c1_6", "coreTestElement.coreTestComponent")
comp_c1_6.addParams({
     "workPerCycle" : "1000",
     "commSize" : "100",
     "commFreq" : "1000"
})
comp_c1_6.setCoordinates(0, 0, 0)
comp_c1_6.addLink(link_id_00000071, "Slink", "10 ns")
comp_c1_6.addLink(link_id_00000083, "Wlink", "10 ns")
link_id_00000085 = sst.Link("link_id_00000085")
comp_c1_6.addLink(link_id_00000085, "Nlink", "10 ns")
link_id_00000086 = sst.Link("link_id_00000086")
comp_c1_6.addLink(link_id_00000086, "Elink", "10 ns")

comp_c2_6 = sst.Component("c2_6", "coreTestElement.coreTestComponent")
comp_c2_6.addParams({
     "workPerCycle" : "1000",
     "commSize" : "100",
     "commFreq" : "1000"
})
comp_c2_6.setCoordinates(0, 0, 0)
comp_c2_6.addLink(link_id_00000073, "Slink", "10 ns")
comp_c2_6.addLink(link_id_00000086, "Wlink", "10 ns")
link_id_00000087 = sst.Link("link_id_00000087")
comp_c2_6.addLink(link_id_00000087, "Nlink", "10 ns")
link_id_00000088 = sst.Link("link_id_00000088")
comp_c2_6.addLink(link_id_00000088, "Elink", "10 ns")

comp_c3_6 = sst.Component("c3_6", "coreTestElement.coreTestComponent")
comp_c3_6.addParams({
     "workPerCycle" : "1000",
     "commSize" : "100",
     "commFreq" : "1000"
})
comp_c3_6.setCoordinates(0, 0, 0)
comp_c3_6.addLink(link_id_00000075, "Slink", "10 ns")
comp_c3_6.addLink(link_id_00000088, "Wlink", "10 ns")
link_id_00000089 = sst.Link("link_id_00000089")
comp_c3_6.addLink(link_id_00000089, "Nlink", "10 ns")
link_id_0000008a = sst.Link("link_id_0000008a")
comp_c3_6.addLink(link_id_0000008a, "Elink", "10 ns")

comp_c4_6 = sst.Component("c4_6", "coreTestElement.coreTestComponent")
comp_c4_6.addParams({
     "workPerCycle" : "1000",
     "commSize" : "100",
     "commFreq" : "1000"
})
comp_c4_6.setCoordinates(0, 0, 0)
comp_c4_6.addLink(link_id_00000077, "Slink", "10 ns")
comp_c4_6.addLink(link_id_0000008a, "Wlink", "10 ns")
link_id_0000008b = sst.Link("link_id_0000008b")
comp_c4_6.addLink(link_id_0000008b, "Nlink", "10 ns")
link_id_0000008c = sst.Link("link_id_0000008c")
comp_c4_6.addLink(link_id_0000008c, "Elink", "10 ns")

comp_c5_6 = sst.Component("c5_6", "coreTestElement.coreTestComponent")
comp_c5_6.addParams({
     "workPerCycle" : "1000",
     "commSize" : "100",
     "commFreq" : "1000"
})
comp_c5_6.setCoordinates(0, 0, 0)
comp_c5_6.addLink(link_id_00000079, "Slink", "10 ns")
comp_c5_6.addLink(link_id_0000008c, "Wlink", "10 ns")
link_id_0000008d = sst.Link("link_id_0000008d")
comp_c5_6.addLink(link_id_0000008d, "Nlink", "10 ns")
link_id_0000008e = sst.Link("link_id_0000008e")
comp_c5_6.addLink(link_id_0000008e, "Elink", "10 ns")

comp_c6_6 = sst.Component("c6_6", "coreTestElement.coreTestComponent")
comp_c6_6.addParams({
     "workPerCycle" : "1000",
     "commSize" : "100",
     "commFreq" : "1000"
})
comp_c6_6.setCoordinates(0, 0, 0)
comp_c6_6.addLink(link_id_0000007b, "Slink", "10 ns")
comp_c6_6.addLink(link_id_0000008e, "Wlink", "10 ns")
link_id_0000008f = sst.Link("link_id_0000008f")
comp_c6_6.addLink(link_id_0000008f, "Nlink", "10 ns")
link_id_00000090 = sst.Link("link_id_00000090")
comp_c6_6.addLink(link_id_00000090, "Elink", "10 ns")

comp_c7_6 = sst.Component("c7_6", "coreTestElement.coreTestComponent")
comp_c7_6.addParams({
     "workPerCycle" : "1000",
     "commSize" : "100",
     "commFreq" : "1000"
})
comp_c7_6.setCoordinates(0, 0, 0)
comp_c7_6.addLink(link_id_0000007d, "Slink", "10 ns")
comp_c7_6.addLink(link_id_00000090, "Wlink", "10 ns")
link_id_00000091 = sst.Link("link_id_00000091")
comp_c7_6.addLink(link_id_00000091, "Nlink", "10 ns")
link_id_00000092 = sst.Link("link_id_00000092")
comp_c7_6.addLink(link_id_00000092, "Elink", "10 ns")

comp_c8_6 = sst.Component("c8_6", "coreTestElement.coreTestComponent")
comp_c8_6.addParams({
     "workPerCycle" : "1000",
     "commSize" : "100",
     "commFreq" : "1000"
})
comp_c8_6.setCoordinates(0, 0, 0)
comp_c8_6.addLink(link_id_0000007f, "Slink", "10 ns")
comp_c8_6.addLink(link_id_00000092, "Wlink", "10 ns")
link_id_00000093 = sst.Link("link_id_00000093")
comp_c8_6.addLink(link_id_00000093, "Nlink", "10 ns")
link_id_00000094 = sst.Link("link_id_00000094")
comp_c8_6.addLink(link_id_00000094, "Elink", "10 ns")

comp_c9_6 = sst.Component("c9_6", "coreTestElement.coreTestComponent")
comp_c9_6.addParams({
     "workPerCycle" : "1000",
     "commSize" : "100",
     "commFreq" : "1000"
})
comp_c9_6.setCoordinates(0, 0, 0)
comp_c9_6.addLink(link_id_00000081, "Slink", "10 ns")
comp_c9_6.addLink(link_id_00000084, "Elink", "10 ns")
comp_c9_6.addLink(link_id_00000094, "Wlink", "10 ns")
link_id_00000095 = sst.Link("link_id_00000095")
comp_c9_6.addLink(link_id_00000095, "Nlink", "10 ns")

comp_c0_7 = sst.Component("c0_7", "coreTestElement.coreTestComponent")
comp_c0_7.addParams({
     "workPerCycle" : "1000",
     "commSize" : "100",
     "commFreq" : "1000"
})
comp_c0_7.setCoordinates(0, 0, 0)
comp_c0_7.addLink(link_id_00000082, "Slink", "10 ns")
link_id_00000096 = sst.Link("link_id_00000096")
comp_c0_7.addLink(link_id_00000096, "Nlink", "10 ns")
link_id_00000097 = sst.Link("link_id_00000097")
comp_c0_7.addLink(link_id_00000097, "Elink", "10 ns")
link_id_00000098 = sst.Link("link_id_00000098")
comp_c0_7.addLink(link_id_00000098, "Wlink", "10 ns")

comp_c1_7 = sst.Component("c1_7", "coreTestElement.coreTestComponent")
comp_c1_7.addParams({
     "workPerCycle" : "1000",
     "commSize" : "100",
     "commFreq" : "1000"
})
comp_c1_7.setCoordinates(0, 0, 0)
comp_c1_7.addLink(link_id_00000085, "Slink", "10 ns")
comp_c1_7.addLink(link_id_00000097, "Wlink", "10 ns")
link_id_00000099 = sst.Link("link_id_00000099")
comp_c1_7.addLink(link_id_00000099, "Nlink", "10 ns")
link_id_0000009a = sst.Link("link_id_0000009a")
comp_c1_7.addLink(link_id_0000009a, "Elink", "10 ns")

comp_c2_7 = sst.Component("c2_7", "coreTestElement.coreTestComponent")
comp_c2_7.addParams({
     "workPerCycle" : "1000",
     "commSize" : "100",
     "commFreq" : "1000"
})
comp_c2_7.setCoordinates(0, 0, 0)
comp_c2_7.addLink(link_id_00000087, "Slink", "10 ns")
comp_c2_7.addLink(link_id_0000009a, "Wlink", "10 ns")
link_id_0000009b = sst.Link("link_id_0000009b")
comp_c2_7.addLink(link_id_0000009b, "Nlink", "10 ns")
link_id_0000009c = sst.Link("link_id_0000009c")
comp_c2_7.addLink(link_id_0000009c, "Elink", "10 ns")

comp_c3_7 = sst.Component("c3_7", "coreTestElement.coreTestComponent")
comp_c3_7.addParams({
     "workPerCycle" : "1000",
     "commSize" : "100",
     "commFreq" : "1000"
})
comp_c3_7.setCoordinates(0, 0, 0)
comp_c3_7.addLink(link_id_00000089, "Slink", "10 ns")
comp_c3_7.addLink(link_id_0000009c, "Wlink", "10 ns")
link_id_0000009d = sst.Link("link_id_0000009d")
comp_c3_7.addLink(link_id_0000009d, "Nlink", "10 ns")
link_id_0000009e = sst.Link("link_id_0000009e")
comp_c3_7.addLink(link_id_0000009e, "Elink", "10 ns")

comp_c4_7 = sst.Component("c4_7", "coreTestElement.coreTestComponent")
comp_c4_7.addParams({
     "workPerCycle" : "1000",
     "commSize" : "100",
     "commFreq" : "1000"
})
comp_c4_7.setCoordinates(0, 0, 0)
comp_c4_7.addLink(link_id_0000008b, "Slink", "10 ns")
comp_c4_7.addLink(link_id_0000009e, "Wlink", "10 ns")
link_id_0000009f = sst.Link("link_id_0000009f")
comp_c4_7.addLink(link_id_0000009f, "Nlink", "10 ns")
link_id_000000a0 = sst.Link("link_id_000000a0")
comp_c4_7.addLink(link_id_000000a0, "Elink", "10 ns")

comp_c5_7 = sst.Component("c5_7", "coreTestElement.coreTestComponent")
comp_c5_7.addParams({
     "workPerCycle" : "1000",
     "commSize" : "100",
     "commFreq" : "1000"
})
comp_c5_7.setCoordinates(0, 0, 0)
comp_c5_7.addLink(link_id_0000008d, "Slink", "10 ns")
comp_c5_7.addLink(link_id_000000a0, "Wlink", "10 ns")
link_id_000000a1 = sst.Link("link_id_000000a1")
comp_c5_7.addLink(link_id_000000a1, "Nlink", "10 ns")
link_id_000000a2 = sst.Link("link_id_000000a2")
comp_c5_7.addLink(link_id_000000a2, "Elink", "10 ns")

comp_c6_7 = sst.Component("c6_7", "coreTestElement.coreTestComponent")
comp_c6_7.addParams({
     "workPerCycle" : "1000",
     "commSize" : "100",
     "commFreq" : "1000"
})
comp_c6_7.setCoordinates(0, 0, 0)
comp_c6_7.addLink(link_id_0000008f, "Slink", "10 ns")
comp_c6_7.addLink(link_id_000000a2, "Wlink", "10 ns")
link_id_000000a3 = sst.Link("link_id_000000a3")
comp_c6_7.addLink(link_id_000000a3, "Nlink", "10 ns")
link_id_000000a4 = sst.Link("link_id_000000a4")
comp_c6_7.addLink(link_id_000000a4, "Elink", "10 ns")

comp_c7_7 = sst.Component("c7_7", "coreTestElement.coreTestComponent")
comp_c7_7.addParams({
     "workPerCycle" : "1000",
     "commSize" : "100",
     "commFreq" : "1000"
})
comp_c7_7.setCoordinates(0, 0, 0)
comp_c7_7.addLink(link_id_00000091, "Slink", "10 ns")
comp_c7_7.addLink(link_id_000000a4, "Wlink", "10 ns")
link_id_000000a5 = sst.Link("link_id_000000a5")
comp_c7_7.addLink(link_id_000000a5, "Nlink", "10 ns")
link_id_000000a6 = sst.Link("link_id_000000a6")
comp_c7_7.addLink(link_id_000000a6, "Elink", "10 ns")

comp_c8_7 = sst.Component("c8_7", "coreTestElement.coreTestComponent")
comp_c8_7.addParams({
     "workPerCycle" : "1000",
     "commSize" : "100",
     "commFreq" : "1000"
})
comp_c8_7.setCoordinates(0, 0, 0)
comp_c8_7.addLink(link_id_00000093, "Slink", "10 ns")
comp_c8_7.addLink(link_id_000000a6, "Wlink", "10 ns")
link_id_000000a7 = sst.Link("link_id_000000a7")
comp_c8_7.addLink(link_id_000000a7, "Nlink", "10 ns")
link_id_000000a8 = sst.Link("link_id_000000a8")
comp_c8_7.addLink(link_id_000000a8, "Elink", "10 ns")

comp_c9_7 = sst.Component("c9_7", "coreTestElement.coreTestComponent")
comp_c9_7.addParams({
     "workPerCycle" : "1000",
     "commSize" : "100",
     "commFreq" : "1000"
})
comp_c9_7.setCoordinates(0, 0, 0)
comp_c9_7.addLink(link_id_00000095, "Slink", "10 ns")
comp_c9_7.addLink(link_id_00000098, "Elink", "10 ns")
comp_c9_7.addLink(link_id_000000a8, "Wlink", "10 ns")
link_id_000000a9 = sst.Link("link_id_000000a9")
comp_c9_7.addLink(link_id_000000a9, "Nlink", "10 ns")

comp_c0_8 = sst.Component("c0_8", "coreTestElement.coreTestComponent")
comp_c0_8.addParams({
     "workPerCycle" : "1000",
     "commSize" : "100",
     "commFreq" : "1000"
})
comp_c0_8.setCoordinates(0, 0, 0)
comp_c0_8.addLink(link_id_00000096, "Slink", "10 ns")
link_id_000000aa = sst.Link("link_id_000000aa")
comp_c0_8.addLink(link_id_000000aa, "Nlink", "10 ns")
link_id_000000ab = sst.Link("link_id_000000ab")
comp_c0_8.addLink(link_id_000000ab, "Elink", "10 ns")
link_id_000000ac = sst.Link("link_id_000000ac")
comp_c0_8.addLink(link_id_000000ac, "Wlink", "10 ns")

comp_c1_8 = sst.Component("c1_8", "coreTestElement.coreTestComponent")
comp_c1_8.addParams({
     "workPerCycle" : "1000",
     "commSize" : "100",
     "commFreq" : "1000"
})
comp_c1_8.setCoordinates(0, 0, 0)
comp_c1_8.addLink(link_id_00000099, "Slink", "10 ns")
comp_c1_8.addLink(link_id_000000ab, "Wlink", "10 ns")
link_id_000000ad = sst.Link("link_id_000000ad")
comp_c1_8.addLink(link_id_000000ad, "Nlink", "10 ns")
link_id_000000ae = sst.Link("link_id_000000ae")
comp_c1_8.addLink(link_id_000000ae, "Elink", "10 ns")

comp_c2_8 = sst.Component("c2_8", "coreTestElement.coreTestComponent")
comp_c2_8.addParams({
     "workPerCycle" : "1000",
     "commSize" : "100",
     "commFreq" : "1000"
})
comp_c2_8.setCoordinates(0, 0, 0)
comp_c2_8.addLink(link_id_0000009b, "Slink", "10 ns")
comp_c2_8.addLink(link_id_000000ae, "Wlink", "10 ns")
link_id_000000af = sst.Link("link_id_000000af")
comp_c2_8.addLink(link_id_000000af, "Nlink", "10 ns")
link_id_000000b0 = sst.Link("link_id_000000b0")
comp_c2_8.addLink(link_id_000000b0, "Elink", "10 ns")

comp_c3_8 = sst.Component("c3_8", "coreTestElement.coreTestComponent")
comp_c3_8.addParams({
     "workPerCycle" : "1000",
     "commSize" : "100",
     "commFreq" : "1000"
})
comp_c3_8.setCoordinates(0, 0, 0)
comp_c3_8.addLink(link_id_0000009d, "Slink", "10 ns")
comp_c3_8.addLink(link_id_000000b0, "Wlink", "10 ns")
link_id_000000b1 = sst.Link("link_id_000000b1")
comp_c3_8.addLink(link_id_000000b1, "Nlink", "10 ns")
link_id_000000b2 = sst.Link("link_id_000000b2")
comp_c3_8.addLink(link_id_000000b2, "Elink", "10 ns")

comp_c4_8 = sst.Component("c4_8", "coreTestElement.coreTestComponent")
comp_c4_8.addParams({
     "workPerCycle" : "1000",
     "commSize" : "100",
     "commFreq" : "1000"
})
comp_c4_8.setCoordinates(0, 0, 0)
comp_c4_8.addLink(link_id_0000009f, "Slink", "10 ns")
comp_c4_8.addLink(link_id_000000b2, "Wlink", "10 ns")
link_id_000000b3 = sst.Link("link_id_000000b3")
comp_c4_8.addLink(link_id_000000b3, "Nlink", "10 ns")
link_id_000000b4 = sst.Link("link_id_000000b4")
comp_c4_8.addLink(link_id_000000b4, "Elink", "10 ns")

comp_c5_8 = sst.Component("c5_8", "coreTestElement.coreTestComponent")
comp_c5_8.addParams({
     "workPerCycle" : "1000",
     "commSize" : "100",
     "commFreq" : "1000"
})
comp_c5_8.setCoordinates(0, 0, 0)
comp_c5_8.addLink(link_id_000000a1, "Slink", "10 ns")
comp_c5_8.addLink(link_id_000000b4, "Wlink", "10 ns")
link_id_000000b5 = sst.Link("link_id_000000b5")
comp_c5_8.addLink(link_id_000000b5, "Nlink", "10 ns")
link_id_000000b6 = sst.Link("link_id_000000b6")
comp_c5_8.addLink(link_id_000000b6, "Elink", "10 ns")

comp_c6_8 = sst.Component("c6_8", "coreTestElement.coreTestComponent")
comp_c6_8.addParams({
     "workPerCycle" : "1000",
     "commSize" : "100",
     "commFreq" : "1000"
})
comp_c6_8.setCoordinates(0, 0, 0)
comp_c6_8.addLink(link_id_000000a3, "Slink", "10 ns")
comp_c6_8.addLink(link_id_000000b6, "Wlink", "10 ns")
link_id_000000b7 = sst.Link("link_id_000000b7")
comp_c6_8.addLink(link_id_000000b7, "Nlink", "10 ns")
link_id_000000b8 = sst.Link("link_id_000000b8")
comp_c6_8.addLink(link_id_000000b8, "Elink", "10 ns")

comp_c7_8 = sst.Component("c7_8", "coreTestElement.coreTestComponent")
comp_c7_8.addParams({
     "workPerCycle" : "1000",
     "commSize" : "100",
     "commFreq" : "1000"
})
comp_c7_8.setCoordinates(0, 0, 0)
comp_c7_8.addLink(link_id_000000a5, "Slink", "10 ns")
comp_c7_8.addLink(link_id_000000b8, "Wlink", "10 ns")
link_id_000000b9 = sst.Link("link_id_000000b9")
comp_c7_8.addLink(link_id_000000b9, "Nlink", "10 ns")
link_id_000000ba = sst.Link("link_id_000000ba")
comp_c7_8.addLink(link_id_000000ba, "Elink", "10 ns")

comp_c8_8 = sst.Component("c8_8", "coreTestElement.coreTestComponent")
comp_c8_8.addParams({
     "workPerCycle" : "1000",
     "commSize" : "100",
     "commFreq" : "1000"
})
comp_c8_8.setCoordinates(0, 0, 0)
comp_c8_8.addLink(link_id_000000a7, "Slink", "10 ns")
comp_c8_8.addLink(link_id_000000ba, "Wlink", "10 ns")
link_id_000000bb = sst.Link("link_id_000000bb")
comp_c8_8.addLink(link_id_000000bb, "Nlink", "10 ns")
link_id_000000bc = sst.Link("link_id_000000bc")
comp_c8_8.addLink(link_id_000000bc, "Elink", "10 ns")

comp_c9_8 = sst.Component("c9_8", "coreTestElement.coreTestComponent")
comp_c9_8.addParams({
     "workPerCycle" : "1000",
     "commSize" : "100",
     "commFreq" : "1000"
})
comp_c9_8.setCoordinates(0, 0, 0)
comp_c9_8.addLink(link_id_000000a9, "Slink", "10 ns")
comp_c9_8.addLink(link_id_000000ac, "Elink", "10 ns")
comp_c9_8.addLink(link_id_000000bc, "Wlink", "10 ns")
link_id_000000bd = sst.Link("link_id_000000bd")
comp_c9_8.addLink(link_id_000000bd, "Nlink", "10 ns")

comp_c0_9 = sst.Component("c0_9", "coreTestElement.coreTestComponent")
comp_c0_9.addParams({
     "workPerCycle" : "1000",
     "commSize" : "100",
     "commFreq" : "1000"
})
comp_c0_9.setCoordinates(0, 0, 0)
comp_c0_9.addLink(link_id_00000001, "Nlink", "10 ns")
comp_c0_9.addLink(link_id_000000aa, "Slink", "10 ns")
link_id_000000be = sst.Link("link_id_000000be")
comp_c0_9.addLink(link_id_000000be, "Elink", "10 ns")
link_id_000000bf = sst.Link("link_id_000000bf")
comp_c0_9.addLink(link_id_000000bf, "Wlink", "10 ns")

comp_c1_9 = sst.Component("c1_9", "coreTestElement.coreTestComponent")
comp_c1_9.addParams({
     "workPerCycle" : "1000",
     "commSize" : "100",
     "commFreq" : "1000"
})
comp_c1_9.setCoordinates(0, 0, 0)
comp_c1_9.addLink(link_id_00000005, "Nlink", "10 ns")
comp_c1_9.addLink(link_id_000000ad, "Slink", "10 ns")
comp_c1_9.addLink(link_id_000000be, "Wlink", "10 ns")
link_id_000000c0 = sst.Link("link_id_000000c0")
comp_c1_9.addLink(link_id_000000c0, "Elink", "10 ns")

comp_c2_9 = sst.Component("c2_9", "coreTestElement.coreTestComponent")
comp_c2_9.addParams({
     "workPerCycle" : "1000",
     "commSize" : "100",
     "commFreq" : "1000"
})
comp_c2_9.setCoordinates(0, 0, 0)
comp_c2_9.addLink(link_id_00000008, "Nlink", "10 ns")
comp_c2_9.addLink(link_id_000000af, "Slink", "10 ns")
comp_c2_9.addLink(link_id_000000c0, "Wlink", "10 ns")
link_id_000000c1 = sst.Link("link_id_000000c1")
comp_c2_9.addLink(link_id_000000c1, "Elink", "10 ns")

comp_c3_9 = sst.Component("c3_9", "coreTestElement.coreTestComponent")
comp_c3_9.addParams({
     "workPerCycle" : "1000",
     "commSize" : "100",
     "commFreq" : "1000"
})
comp_c3_9.setCoordinates(0, 0, 0)
comp_c3_9.addLink(link_id_0000000b, "Nlink", "10 ns")
comp_c3_9.addLink(link_id_000000b1, "Slink", "10 ns")
comp_c3_9.addLink(link_id_000000c1, "Wlink", "10 ns")
link_id_000000c2 = sst.Link("link_id_000000c2")
comp_c3_9.addLink(link_id_000000c2, "Elink", "10 ns")

comp_c4_9 = sst.Component("c4_9", "coreTestElement.coreTestComponent")
comp_c4_9.addParams({
     "workPerCycle" : "1000",
     "commSize" : "100",
     "commFreq" : "1000"
})
comp_c4_9.setCoordinates(0, 0, 0)
comp_c4_9.addLink(link_id_0000000e, "Nlink", "10 ns")
comp_c4_9.addLink(link_id_000000b3, "Slink", "10 ns")
comp_c4_9.addLink(link_id_000000c2, "Wlink", "10 ns")
link_id_000000c3 = sst.Link("link_id_000000c3")
comp_c4_9.addLink(link_id_000000c3, "Elink", "10 ns")

comp_c5_9 = sst.Component("c5_9", "coreTestElement.coreTestComponent")
comp_c5_9.addParams({
     "workPerCycle" : "1000",
     "commSize" : "100",
     "commFreq" : "1000"
})
comp_c5_9.setCoordinates(0, 0, 0)
comp_c5_9.addLink(link_id_00000011, "Nlink", "10 ns")
comp_c5_9.addLink(link_id_000000b5, "Slink", "10 ns")
comp_c5_9.addLink(link_id_000000c3, "Wlink", "10 ns")
link_id_000000c4 = sst.Link("link_id_000000c4")
comp_c5_9.addLink(link_id_000000c4, "Elink", "10 ns")

comp_c6_9 = sst.Component("c6_9", "coreTestElement.coreTestComponent")
comp_c6_9.addParams({
     "workPerCycle" : "1000",
     "commSize" : "100",
     "commFreq" : "1000"
})
comp_c6_9.setCoordinates(0, 0, 0)
comp_c6_9.addLink(link_id_00000014, "Nlink", "10 ns")
comp_c6_9.addLink(link_id_000000b7, "Slink", "10 ns")
comp_c6_9.addLink(link_id_000000c4, "Wlink", "10 ns")
link_id_000000c5 = sst.Link("link_id_000000c5")
comp_c6_9.addLink(link_id_000000c5, "Elink", "10 ns")

comp_c7_9 = sst.Component("c7_9", "coreTestElement.coreTestComponent")
comp_c7_9.addParams({
     "workPerCycle" : "1000",
     "commSize" : "100",
     "commFreq" : "1000"
})
comp_c7_9.setCoordinates(0, 0, 0)
comp_c7_9.addLink(link_id_00000017, "Nlink", "10 ns")
comp_c7_9.addLink(link_id_000000b9, "Slink", "10 ns")
comp_c7_9.addLink(link_id_000000c5, "Wlink", "10 ns")
link_id_000000c6 = sst.Link("link_id_000000c6")
comp_c7_9.addLink(link_id_000000c6, "Elink", "10 ns")

comp_c8_9 = sst.Component("c8_9", "coreTestElement.coreTestComponent")
comp_c8_9.addParams({
     "workPerCycle" : "1000",
     "commSize" : "100",
     "commFreq" : "1000"
})
comp_c8_9.setCoordinates(0, 0, 0)
comp_c8_9.addLink(link_id_0000001a, "Nlink", "10 ns")
comp_c8_9.addLink(link_id_000000bb, "Slink", "10 ns")
comp_c8_9.addLink(link_id_000000c6, "Wlink", "10 ns")
link_id_000000c7 = sst.Link("link_id_000000c7")
comp_c8_9.addLink(link_id_000000c7, "Elink", "10 ns")

comp_c9_9 = sst.Component("c9_9", "coreTestElement.coreTestComponent")
comp_c9_9.addParams({
     "workPerCycle" : "1000",
     "commSize" : "100",
     "commFreq" : "1000"
})
comp_c9_9.setCoordinates(0, 0, 0)
comp_c9_9.addLink(link_id_0000001d, "Nlink", "10 ns")
comp_c9_9.addLink(link_id_000000bd, "Slink", "10 ns")
comp_c9_9.addLink(link_id_000000bf, "Elink", "10 ns")
comp_c9_9.addLink(link_id_000000c7, "Wlink", "10 ns")

# Define SST Statistics Options:
sst.setStatisticOutput("sst.statOutputConsole")
# End of generated output.

